{{- if eq .Values.mode "headless" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "itl-poc-agent.name" . }}
  labels: {{- include "itl-poc-agent.labels" . | nindent 4 }}
spec:
  selector: {{- include "itl-poc-agent.labels" . | nindent 4 }}
  ports:
    - {name: http, port: {{ .Values.headless.port }}, targetPort: {{ .Values.headless.port }}}
{{- end }}
